### ISSUE TITLE
Aliases aren't documented

### ISSUE THREAD

**Issue by megawac** [caolan/async#1251]
The documentation is missing aliases (e.g. `forEach` and `forEachOf`)

/cc @hargasinski know a quick fix?

**Comment by hargasinski** [comment]
I don't think so, but I'll look at the code tonight. I should be able to have a fix ready sometime this weekend. Thanks for noticing it.

It seems like minami just never implemented support the tag because, from a quick skim of the jsdoc [alias docs](http://usejsdoc.org/tags-alias.html), it looks like the expected behaviour of `@alias` is different then what we're using it for. `@alias` is meant to rename the function, as opposed to adding an actual alias. 

>  For example, when JSDoc processes the following code, it recognizes that foo is a function, then renames `foo` to `bar` in the documentation:
> 
> ```js
> /**
>  * Bar function.
>  * @alias bar
>  */
> function foo() {}
> ```

I'll add a fix for our needs somewhere, most likely in the `theme/publish.js`, and open a PR this weekend.
