### ISSUE TITLE
Calling callback() for a queue task outside of the queue worker implementation?

### ISSUE THREAD

**Issue by martijnvdwoude** [caolan/async#1286]
First time using queue and having a difficult time understanding some stuff. I have several tasks that I want a queue to handle. I need to be able to keep adding tasks at the end of the queue all the time while the tasks in the queue are still being executed. I do this with queue.push(). I use a concurrency of 1 because they need to be executed in series. Some of these tasks require the queue to not proceed to the next task until my Node.js server receives a POST request by the user containing a specific JSON body. For this reason I'm omitting the callback() call in the async.queue() for these cases.

I assumed it would be possible to retrieve the tasks or workersList from the queue somewhere else in the code and manually call callback() on that specific task. But I can't find a way to do this.

```javascript
    var queue = async.queue(function(task, callback) {
        // Do stuff here but don't finish the task yet
        // callback() missing here
    }, 1);

    addTaskToQueue = function(task){
        queue.push(task, function(err) {
            console.log("Task callback called"); // This is not being called
        });
    };

    finishTask = function() {
        queue.workersList()[0].callback(); // I need to call callback() on the task, how to do it?
    };
```

**Comment by martijnvdwoude** [comment]
Alright, I managed to call callback() where I intended to. Except it seems that the queue isn't being drained/emptied this way. Is that correct and how can I fix that?

**Comment by hargasinski** [comment]
This occurs because the `callback` passed to the `worker` function, and the `callback` you call at `queue.workersList()[i].callback` are different. 

The `callback` passed to `worker` does a couple extra checks (such as check if it needs to call `drain` and `unsaturated`) in addition to also calling the actual `callback` (the function passed to `push`). When you call `queue.workersList()[i].callback()`, you're calling the actual `callback` passed to `push`, and therefore, bypassing all of these checks. 

Since you're executing these tasks in series, a hacky way of accomplishing what you need to would be:
```js
var taskCallback = null;
var queue = async.queue(function(task, callback) {
    taskCallback = callback;
    // Do stuff here but don't finish the task yet    
}, 1);

// rest of your code

var finishTask = function() {
    if (taskCallback) taskCallback();
};
```
Note: if you call `finishTask` too early, you will move onto the next task while the previous one is still executing.

You could also look into including an `[async.until](http://caolan.github.io/async/docs.html#.until)` near the end of your task, where `test` would return if the data from the user has been received, and `callback` would the task's callback. You would just an asynchronous `noop` as `fn`.

**Comment by martijnvdwoude** [comment]
I didn't consider the possibility the callback functions were different. Makes a lot of sense, how else should it know to finish a task. I also thought of keeping a reference to the callback in the way you mentioned, which worked, but wanted to avoid it at first. I'm now keeping the callbacks in an array and remove them when I call ```finishTask```. The data for every task has an ID so I can reliably finish and remove them from the array that way, and because the whole mechanism works in series, in my case there is no risk of calling ```finishTask``` too early. Thanks!
