### ISSUE TITLE
Odd result from waterfall

### ISSUE THREAD

**Issue by ath88** [caolan/async#1298]
**What version of async are you using?**
2.0.1

**Which environment did the issue occur in (Node version/browser version)**
Node 6.7.0

**What did you do? Please include a minimal reproducable case illustrating issue.**
``` javascript
require("async").waterfall([
    (callback) => callback()
], (error) => console.log(error));
```

**What did you expect to happen?**
In `async@1.5.2`, in the above case `error` is undefined. 

**What was the actual result?**
In `async@2.0.1`, in the above case `error` is `null`. The final callback is somehow called with `callback(null)` which probably should have been `callback()`.

This may be working as indended, but its just something I noticed had changed recently.

**Comment by hargasinski** [comment]
Thanks for the report @ath88! This is working as expected. The reason for this change was to standardise the value of `error` passed to the final callback, if an error was not detected during execution. Many of the other functions in `v1.5.x` that run tasks in series, similar to `waterfall`, like `mapSeries`, `eachOfSeries`, etc..., were already passing `null` to the final callback, even if a different, falsy value was passed into `callback` on the final iteration. `Waterfall` was an exception. 

This was standardised in `v2.0`, so that all functions pass `null` to their final callback if they don't detect an error during execution. The reason for standardising it is that it will allow us to implement a number of cool, new features in the future. For instance, breaking out of a flow early if a value of `false` was explicitly passed as `error`.



it wasn't standardised what the value of `error` was, if a falsy value was passed to the final callback. For instance, functions such as `map`, `each`, and `eachOf` always passed `null` as `error` if they didn't detect an error during execution, while functions such as `waterfall`,

**Comment by ath88** [comment]
Oh, cool! I did not see that coming. :) Thanks for clarifying this. :)

**Comment by hargasinski** [comment]
No worries :)
