### ISSUE TITLE
Can whilst return result to iteratee?

### ISSUE THREAD

**Issue by danielflippance** [caolan/async#1330]
I was successfully running whilst like this to read records from a stream:

	async.whilst(
		function () { record = parser.read(); return record; },
		function (done) {
			if (record.Name.toLowerCase() === 'name') { ...

When I moved to strict mode, the record is no longer declared in the iteratee, so record.Name now fails. Is there another way to do this with async?

**Comment by hargasinski** [comment]
Hi @danielflippance, you can try defining `record` before the `async.whilst` call, or in the global scope. That's actually what happens when you declare a variable without the `var` keyword when not in strict mode. See [this Stack Overflow question](http://stackoverflow.com/questions/1470488/what-is-the-purpose-of-the-var-keyword-and-when-to-use-it-or-omit-it) for a little more details.

Your code would change to:
```js
'use strict';

var record;
async.whilst(
	function () { record = parser.read(); return record; },
	function (done) {
		if (record.Name.toLowerCase() === 'name') { ...
```
You can look at the [whilst docs](http://caolan.github.io/async/docs.html#whilst) for another example.

As to answer your first question, `whilst` doesn't pass values from the test function to the iteratee directly. The return value of `test` is only used to determine whether or not to continue running the iteratee.

**Comment by megawac** [comment]
Another option would be to use [`during`](http://caolan.github.io/async/docs.html#doDuring) which will pass arguments from the iteratee to the testfn

```js
async.whilst(
  function iteratee(callback) { 
    var record = parser.read();
    callback(null, record);
  },
  function testFn(record, done) {
    if (!record) {
      return false;
    }
    if (record.Name.toLowerCase() === 'name') { ... }
```

Note: in this approach your iteratee function is simply responsible for getting the data, and your test function will be doing all the work.
