### ISSUE TITLE
Searching aliases in documentation

### ISSUE THREAD

**Issue by megawac** [caolan/async#1339]
@hargasinski would it be possible to search aliases in the documentation search bar? For example, I always search for `find` and then remember that its called `detect`

**Comment by hargasinski** [comment]
Definitely. I'll look into it this evening/weekend. Thanks for the heads up.

**Comment by megawac** [comment]
Awesome thanks! Just bringing it up because I saw a couple SO posts with confusion on some of the aliases

**Comment by hargasinski** [comment]
Quick question, did you notice the source files not appearing when searching before? For some reason, typeahead would occasionally throw an error for me about `setImmediate` not being function. I know typeahead hasn't been updated for awhile, so I don't know what would've changed. I just added a reference to `async.setImmediate` and the problem was fixed, but it still seemed really odd.

Aside from that it was a quick fix. I don't know if I should add the aliases to the toc now too (see #1340).
