### ISSUE TITLE
Should async.reduce iteratee contain currentIndex and array?

### ISSUE THREAD

**Issue by jingsam** [caolan/async#1383]
Should async.reduce iteratee contain currentIndex and array? Just like the standard Array.reduce?
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/Reduce

**Comment by megawac** [comment]
Perhaps, but if you're doing anything that requires the iterators `index` or `key` I think you would be better served by `transform`.

The reason we decided not to include the key there is the primary use case was to do something with the value and then call the callback.

Do you have a use case that would have been better served with an indexed `reduce` than `transform`?

**Comment by aearly** [comment]
Since the iteratee callback has to be the last arg, it is ambiguous as to whether your iteratee would actually use the index or array.  In other words, there's no way to support both `async.reduce(arr, (acc, value, next) => {}, cb)` and `async.reduce(arr, (acc, value, index, array, next) => {}, cb)`.

If you need the index, make a new array that has what you need as the values:

```js
let pairArray = _.pairs(arr);
async.reduce(pairArray, (acc, [index, value], next) => {
  //...
}, done);
```
