### ISSUE TITLE
feature request - big one - async.autoInjectCached

### ISSUE THREAD

**Issue by ORESoftware** [caolan/async#1400]
I love `async.autoInject`, as you may know. 

Now, I have a use case, where I would like to use async.autoInject, call the same routine multiple times, and have `async.autoInject` cache the values that have already been procured. If the values have already been procured, it wouldn't recall the subroutines, it would just call

```js
process.nextTick(function(){
   cb(null, cachedValue);
});
```

It would be super nice for my use case. What do you think? I supposed it could be called `async.autoInjectCached` or something like that. Not sure how the implementation would work though; the user (me) might have to pass a unique id to `async.autoInjectCached`, and then async would use that id as the key to store/retrieve the cached values.

So something like this:

```js
async.autoInjectCached('<id>', {
    get_data: function(callback) {
        // async code to get some data
        callback(null, 'data', 'converted to array');
    },
    make_folder: function(callback) {
        // async code to create a directory to store a file in
        // this is run at the same time as getting the data
        callback(null, 'folder');
    },
    write_file: function(get_data, make_folder, callback) {
        // once there is some data and the directory exists,
        // write the data to a file in the directory
        callback(null, 'filename');
    },
    email_link: function(write_file, callback) {
        // once the file is written let's email a link to it...
        // write_file contains the filename returned by write_file.
        callback(null, {'file':write_file, 'email':'user@example.com'});
    }
}, function(err, results) {
    console.log('err = ', err);
    console.log('email_link = ', results.email_link);
});
```

I think the id passed as the first param is all the extra info that is really needed.

Of course, async.autoInject might not be the only benefactor of caching, maybe caching could be applied to other utilities too, curious about that. Maybe caching features are already implemented in some async utilities, but I doubt that.

`async.autoInjectWithCache` might be a better name

**Comment by hargasinski** [comment]
Hey @ORESoftware, thanks for the feature request! Would using [`auto`](http://caolan.github.io/async/docs.html#auto) (or `autoInject` with expliciting passing the names of parameters) and wrapping each task in [`memoize`](http://caolan.github.io/async/docs.html#memoize) fit your use case? `memoize` uses the first argument, or optionally, a hashing function, to cache the results of the function call. 

Otherwise, if you have a routine that calls `autoInject` and is passed an `id`, you might be able to wrap it in `memoize`.

**Comment by ORESoftware** [comment]
@hargasinski that might work - I'd like to use this as part of an API, so I want to put less burden on the end user, wrapping in memoize might be too much work for them, etc.

**Comment by ORESoftware** [comment]
@hargasinski yeah I looked into it, essentially what I am looking for is for async lib to do the work of calling memoize internally, using the <id> that I mention above, along with the unique name of each task, for cache lookup.

**Comment by aearly** [comment]
I think having the task functions defer to memoized functions (or otherwise cached functions) is really what you want here.  You could even cache part of the `autoInject` flow you know will be commonly re-used and pass it as the first step of another `autoInject` flow.

The reason I'm hesitant to add this is because caching is hard (especially cache eviction), and there are may ways to do it.  There are dozens of caching libraries on npm that each handle it each in their own way, depending on what you need.  In my experience, as some point caching in Node also breaks down, and you need to start caching in something like Redis.  Suddenly we're outside the domain of a control-flow library.
