### ISSUE TITLE
parallelLimit only fires limit number of functions

### ISSUE THREAD

**Issue by freeman-g** [caolan/async#1469]
**What version of async are you using?**
2.5.0

**Which environment did the issue occur in (Node version/browser version)**
Chrome 60

**What did you do? Please include a minimal reproducable case illustrating issue.**
For example, I'm giving a list of 10 async axios functions to parallelLimit with a limit of 5 and only the first 5 are called.  

**What did you expect to happen?**
I expected the remaining tasks to be called individually as soon as each task from the first batch is finished.

**What was the actual result?**
Only the first 5 functions are called.  The remaining 5 are never called.

Here's some example code of what I am doing:

```
        let taskList = []
        for (let i = 0; i < 10; i++) {
          let postFunc = () => {
            axios.post(process.env.API_BASE_URL + '/api/mypostendpoint/', params, { responseType: 'arraybuffer' }).then(response => {
              // do something with the data
            }, error => {
              // handle error
            })
          }
          taskList.push(postFunc)
        }

        let logger = () => {
          console.log('we are done')
        }
        parallelLimit(taskList, 5, logger)

        // logger is never called and the last 5 functions are never called

```

**Comment by hargasinski** [comment]
Hi @freeman-g, thanks for the question!

For async to know a task finished (i.e. to run the next one), the task needs to call the `callback` passed to it. Otherwise `parallelLimit` will wait indefinitely for the first 5 tasks to finish running.

```js
let postFunc = (callback) => {
  axios.post(process.env.API_BASE_URL + '/api/mypostendpoint/', params, { responseType: 'arraybuffer'}).then(response => {
    // do something with the data
    return callback(null)
  }, error => {
    // handle error
    return callback(err)
  })
}
```

If you change `postFunc` to return the promise, you could use [asyncify](http://caolan.github.io/async/docs.html#asyncify) to do this automatically. 

```js
let postFunc = () => {
  return axios.post(process.env.API_BASE_URL + '/api/mypostendpoint/', params, { responseType: 'arraybuffer' }).then(response => {
    // do something with the data
  }, error => {
    // handle error
  })
}
taskList.push(asyncify(postFunc))
```
See the [asyncify](http://caolan.github.io/async/docs.html#asyncify) and [parallelLimit](http://caolan.github.io/async/docs.html#parallelLimit) docs for more info.

**Comment by freeman-g** [comment]
Thank you, will give that a try
