### ISSUE TITLE
Is it possible to cancel running task ?

### ISSUE THREAD

**Issue by deckbsd** [caolan/async#1487]
**What version of async are you using?**
2.5.0
**Which environment did the issue occur in (Node version/browser version)**
Node js v8
**What did you do? Please include a minimal reproducable case illustrating issue.**
i created a method that call the kill method of a queue object. This method killed all the tasks that was in queue and not running already, but i saw that tasks that ware running were not kill :/ Is there a way to cancel ALL the task of a queue ? because in my case, some task also push new task into the queue , so if one task is still running, it can add more task even if i want to stop everything.
**What did you expect to happen?**
To have all task canceled
**What was the actual result?**
The running tasks were not cancel

**Comment by GFJHogue** [comment]
I don't believe it is possible to _directly_ stop your running tasks because of the single-threaded nature of Node.

A way to achieve the behaviour you're looking for would be to execute your queue of tasks within a [Child Process](https://nodejs.org/api/child_process.html). This way killing the child process would kill your entire queue.

**Comment by deckbsd** [comment]
Oh okay, thanks for the answer :)
