### ISSUE TITLE
Go full ES6 in v3.0?

### ISSUE THREAD

**Issue by aearly** [caolan/async#1541]
Currently, the only ES2015 feature we use is modules, which we compile away down to ES5 in the build process.  As we are gearing up for another batch of breaking changes in the 3.0 release, we could also start using more ES6 features.

Node 4 just left its maintenance period,  meaning we are left with Node 6, 8, and 10, which all have nearly full ES6 support.  The situation for all major browsers is similar.  https://kangax.github.io/compat-table/es6/

Pros:
- Better developer ergonomics, smaller source code size
- Lots of ES6 features (e.g. arrow functions, rest parameters) are faster than their ES5 equivalents
- Can use Maps, Sets, Symbols, generators, Promises, etc.  which are all handy

Cons:
- Users still supporting ES5 environments, e.g. IE11 will have to transpile, which will slow down their builds.  They can elect to keep using v2 however.

**Comment by hargasinski** [comment]
I think I would be in favour of using more ES6 features in the code base.

Since we dropped `lodash` and size isn't as much of a concern anymore, could we include an additional transpiled ES5 version, such as `async/es5` or `async/legacy`, in the package for users that still need to support ES5 environments?

**Comment by cekvenich** [comment]
No. ES5 until IE11 popularity drops.

**Comment by aearly** [comment]
You're welcome to stick with v2, or transpile.
