### ISSUE TITLE
Results is undefined in Async Auto

### ISSUE THREAD

**Issue by rahulsonwalkar** [caolan/async#1548]
**What version of async are you using?**
0.9.0
**Which environment did the issue occur in (Node version/browser version)**
v8.11.2
**What did you do? Please include a minimal reproducable case illustrating issue.**
I ran this example code in [Async Auto Documentation](https://caolan.github.io/async/docs.html#auto).
```
async.auto({
    get_data: function(callback) {
        console.log('in get_data');
        // async code to get some data
        callback(null, 'data', 'converted to array');
    },
    make_folder: function(callback) {
        console.log('in make_folder');
        // async code to create a directory to store a file in
        // this is run at the same time as getting the data
        callback(null, 'folder');
    },
    write_file: ['get_data', 'make_folder', function(results, callback) {
        console.log('in write_file', JSON.stringify(results));
        // once there is some data and the directory exists,
        // write the data to a file in the directory
        callback(null, 'filename');
    }],
    email_link: ['write_file', function(results, callback) {
        console.log('in email_link', JSON.stringify(results));
        // once the file is written let's email a link to it...
        // results.write_file contains the filename returned by write_file.
        callback(null, {'file':results.write_file, 'email':'user@example.com'});
    }]
}, function(err, results) {
    console.log('err = ', err);
    console.log('results = ', results);
});
```
**What did you expect to happen?**
Expected `results` in `write_file` to contain results of `get_data` and `make_folder`.
**What was the actual result?**
`results` is undefined.

**Comment by hargasinski** [comment]
Hi @rahulsonwalkar, thanks for the question!

The docs are for the most recent version of `async`, `v2.6.1`. There have been a couple of breaking changes to `auto` since `v0.9.0`. You should consider updating to a supported version to take advantage of new features and performance improvements, such as the docs.

Looking through [the history](https://github.com/caolan/async/tree/5f62a1bcdda2bc961797ecac8c683128dbdf0aaf#auto), in `v0.9.0`, the parameters passed to a task were flipped with the `callback` coming first.

**Comment by rahulsonwalkar** [comment]
Thanks @hargasinski ! This was helpful.
