### ISSUE TITLE
Does not work with async generators

### ISSUE THREAD

**Issue by cesarvarela** [caolan/async#1551]
Seems so.

**Comment by aearly** [comment]
What would support for async generators look like?  What's an example method in Async you would use with an async generator?

**Comment by abraham** [comment]
I just ran into this same issue. I have a large dataset I would like to iterate over in batches and then queue work for the pull from those async results. This is an example of the pattern I was looking at. There is an API that returns a number of `Things`. I want to process 10 `Things` concurrently dynamically get more `Things` from the API when the pool runs out.

```
interface Thing {
  url: string;
}

const api = {
  page: (page: number) => {
    return {
      url: `https://example.com/page=${page}`,
    }
  }
}

const work = async function*() {
  let things: Thing[] = [];
  while (page < 10) {
    if (things.length === 0) {
      const res = await fetch(api.page(page).url);
      things = await res.json();
    }
    yield String(things.shift())
  }
};

async.eachLimit(work(), 2, async (thing: Thing) => {
  const res = await fetch(thing.url);
  // do stuff with res
});
```

**Comment by cesarvarela** [comment]
So I have to iterate over a large number of items, and I use an async iterable for that, but I want to process these items in parallel with a limit of let's say 100 at a time.

```
const iterable = {}
iterable[Symbol.asyncIterator] = function* () {
    yield 1;
    yield 2;
    yield 3;
}

async.eachLimit(iterable, 100, (item)=> { something(item) }, ()=> {} )

```

**Comment by rockyhuber** [comment]
Hi guys, 
This code seems well beyond my comprehension atm. I am trying to have it so that there is a pool, that sits on the server always waiting for a request from a client. Then when the client performs an action, add that action to the array pool and do the processing on the server and remove it from the pool once the processing has completed. Something like this:

```
let tasksPool = [];

let processTask = async function(task) {
  // await etc
}

eachLimit(tasksPool, 5, function(task, callback) {
  processTask(task).then(() => {
    callback();
  });
});

app.get('/some-url', (req, res) => {
  tasksPool.push(req.body.task);
});
```
But it does not re-fire the eachLimit process when I add something to the array. I want eachLimit to effectively watch the array for changes. I wished I could understand what was going on with your example enough to solve this on my own. Any suggestions appreciated greatly?
