### ISSUE TITLE
TypeError: Cannot read property 'Symbol(Symbol.toStringTag)' of undefined

### ISSUE THREAD

**Issue by Shubhangi-yadav** [caolan/async#1554]
**What version of async are you using?**  "^2.6.1",
**Which environment did the issue occur in (Node version/browser version)**  Node version

**What did you do? Please include a minimal reproducable case illustrating issue.**  

**What did you expect to happen?** I wanted passing values between 2 callbacks using waterfall .
[test.zip](https://github.com/caolan/async/files/2162273/test.zip)

**What was the actual result?** getting an error

**Comment by hargasinski** [comment]
Hi @Shubhangi-yadav, thanks for the question!

See [this SO answer](https://stackoverflow.com/a/336868/5538786) for a more detailed explanation, but essentially you're passing `undefined`, instead of a function, to `waterfall`. If you change your function expressions to function declarations, or move your function expressions to before the call to `waterfall`, everything should work.

i.e. change
```js
var doconnect = function(cb) {
```
to
```js
function doconnect(cb) {
```

**Comment by hargasinski** [comment]
The `callback` passed to a task expects an error as the first argument, or `null` if there is no error. Since you are passing a truthy value, `result.rows.length`, as the first argument, it assumes there is an error and calls the final callback with the error. Changing `return cb( result.rows.length,conn);` to `return cb(null, result.rows.length, conn);` should fix the error.

See the [`waterfall` docs](https://caolan.github.io/async/docs.html#waterfall) for more info.

**Comment by Shubhangi-yadav** [comment]
result.rows.length is showing an error

TypeError: Cannot read property 'length' of undefined

**Comment by hargasinski** [comment]
That question is probably better suited for the [`node-oracledb` docs](https://oracle.github.io/node-oracledb/doc/api.html#-4264-execute-callback-function) or [Stackoverflow](https://stackoverflow.com/questions/tagged/oracledb-npm).

However, quickly skimming the oracledb docs it appears that `results.row` is set to `null` when the SQL statement isn't a `SELECT` statement. See [this](https://oracle.github.io/node-oracledb/doc/api.html#-42644-rows) for more info.

**Comment by Shubhangi-yadav** [comment]
hello , I am having an error while using conn.executeMany command .Please suggest how to resolve it.
[test.zip](https://github.com/caolan/async/files/2183523/test.zip)
