### ISSUE TITLE
Doc versioning and other `v3` doc issues

### ISSUE THREAD

**Issue by hargasinski** [caolan/async#1583]
Right now, when the docs are generated, the new version replaces the previous one. When `v3` comes out, we will need both the `v3` and `v2` docs on the site, and a way to update them individually. Depending on the amount of history we want, this should be fairly straight forward with a script that detects the version being generated from the `package.json`. Should we just have the latest docs for  each major version (`v2`, `v3`), each minor version (`v2.5`, `v2.6`, `v3.0`, `v3.1`, etc...) or each patch version (`v2.6.0`, `v2.6.1`, `v3.0.0`, `v3.0.1`, etc...)? I'm leaning towards having the docs for all the patch versions available on the site and being able to switch between them with the dropdown at the top.

Are there any other doc issues that need to be addressed for `v3`?

**Comment by aearly** [comment]
I think we could get away with docs for just the major versions, e.g. 2.x and 3.x, a la Lodash.

The only thing I can think of for doc issues, is that I'd like to move to a `docs/` folder based approach, rather than the `gh-pages` branch-based approach.  It will make things easier to work on, and also means we can roll out updates without doing a release.

We can do these changes as we want to, no need to block the 3.0 release.

**Comment by aearly** [comment]
Oh, I'd also like to include more async/await examples.  It needs to be more clear how to use async functions as iteratees, and what awaiting Async methods looks like when you leave off a callback.

**Comment by andyedwardsdfdl** [comment]
Well, v3 is now out, and the v2 docs have disappeared from https://caolan.github.io/async/index.html
