### ISSUE TITLE
async.parallel`s function is working after another function has invoked callback function with error, why?

### ISSUE THREAD

**Issue by AbduRasul1996** [caolan/async#1599]
i was learning async library and just tried some codes myself and i am issueing a problem that can`t handle, can you please look at the code down below:)
```
async.parallel([
    function (cb) {
        setTimeout(() => {
          let a = "asd";

          console.log("AAA");
          cb(a, null);

        }, 2000);
    },
    function (cb) {
      setTimeout( () => {
        let b = "dasd";

        console.log("BBBBB");
        cb(b, null);
      }, 5000);
    }
  ], function (error, results) {
    console.log("CCC");

    console.log("Errors: " + error);
    console.log("Results: " + results);
  });
```
I supposed that BBB should NOT output to the screen, but to my surprise it DOES, can you help me understand why?

**Comment by applefreak** [comment]
`console.log("BBBBB");` is invoked immediately when `5000` msec is reached. And then it invokes `cb(b, null);`

Now if you changed `cb(b, null);` to `return cb(b, null);` AND put it before `console.log("BBBBB");`, then it will not get invoked.

**Comment by hargasinski** [comment]
Hi @AbduRasul1996,

Thanks for the question! As @applefreak mentions, `async.parallel`, and generally all `async` functions, don't have a way of stopping a task once it's been started, even if the final callback has already been called. So after `CCC` is logged, the second task is still running, and when the `setTimeout` finishes, it still invokes it's callback, logging `BBBBB`.

The issue stems from `async.parallel` starting all of the tasks at once. If you want to wait for the first task to finish before the second one starts, look into [async.series](https://caolan.github.io/async/docs.html#series). In this case, because the first tasks returns an error, the second task will never be called and `BBBBB` won't be logged.
