### ISSUE TITLE
Relevance of devdeps in Guix

### ISSUE THREAD

**Issue by swedebugia** [caolan/async#1600]
Hi
I'm wondering how many of the devdeps are strictly needed for building async? How many are needed if we want to test it too?

We are trying in Guix to figure out how to package async in a reproducible way.
See also: https://lists.gnu.org/archive/html/guix-devel/2018-11/msg00201.html

I'm using a guile-script to make a graph of async and the devdependencies and all recursive dependencies of those. It is still running and has 235 levels and 823 packages and counting.

This means that if we are to package async with all the devdeps (unlikely needed I hope so) we need first to package 823+ other packages to build the devdeps.

This is a lot.

Cheers 
swedebugia

**Comment by aearly** [comment]
All of the dev deps are relevant to build and test Async. We make no determination between those use to build and those used to test.   If you just want a built version, we distribute `dist/async.js` in every release that has no other dependencies.

However, if you are going to be importing other npm packages, large dependency and devDependency trees are the norm rather than the exception. Be prepared to import thousands of packages.
