### ISSUE TITLE
Queue: Drain/callback triggered automatically after idle?

### ISSUE THREAD

**Issue by lapidus** [caolan/async#1635]
I have a very slow operation that adds to a queue over a duration of 15 minutes.
It seems drain is called prematurely or that the queue somehow times out. Is there a built in timeout controlling this?

**What version of async are you using?**

2.6.1

**Which environment did the issue occur in (Node version/browser version)**

Node 10.15

**Comment by hargasinski** [comment]
Hi @lapidus,

Thanks for the question. There is no builtin timeout controlling `drain`. `drain` is called whenever the `queue` finishes processing all of it's tasks, i.e. there are no tasks running or pending. If your operation is adding tasks slowly, then what is mostly happening is that the `queue` finishes running of all of it's tasks, and becomes `idle` (which is why `drain` is called) before the operation adds more.

See the [QueueObject](https://caolan.github.io/async/docs.html#QueueObject) docs for more info.
