### ISSUE TITLE
what time should i to use this?

### ISSUE THREAD

**Issue by chenbimo** [caolan/async#1816]
**What version of async are you using?**

**Which environment did the issue occur in (Node/browser/Babel/Typescript version)**

**What did you do? Please include a minimal reproducible case illustrating issue.**

**What did you expect to happen?**

**What was the actual result?**

The JavaScript is support async/await/promise now.Sometimes,i don't know what time should i to use this library.

**Comment by LeandroFontellas** [comment]
Thats something that i would like to know too.

**Comment by aearly** [comment]
This library was built for a different time, and I will admit that most of the control flow methods are pretty obsolete: `waterfall`, `parallel`, `series`, etc...  `auto` and `queue` have their uses, especially the concurrency-limiting features.  The collection methods can be useful, though, since they work with both callbacks and `async` functions (and they also have limit features).

**Comment by chenbimo** [comment]
> 

thinks a lot!very useful answer for me.
