### ISSUE TITLE
async.auto with branching

### ISSUE THREAD

**Issue by alexcarruthers** [caolan/async#650]
This is more of a feature request than an issue. I would like something that works a lot like async.auto but instead of each step defining the previous steps that need to complete, each step lets async know which step to run next. this allows for some pretty useful branching (ie run this set of tasks instead of another). the callbacks could be called using a `callback(['nextStep1', 'nextStep2'], return_val)` type syntax

**Comment by aearly** [comment]
I personally like how each `auto` task "pulls" from it's dependencies rather than having to "push" to its dependents.  It's easier to add and remove tasks, and ensure that everything gets to its right place.  The exact execution order isn't obvious, but it shouldn't matter.

If you want the "push" type of behavior, you can do it by nesting `parallel`/`series`/`waterfall`/etc..  A bit cumbersome, but I think doing control flow this way is fundamentally cumbersome.
