### ISSUE TITLE
async.each, why does this code print the error only once?

### ISSUE THREAD

**Issue by AliUz** [caolan/async#767]
```javascript
var arr = [1,2,3,4,5,6,7,8];

async.each(arr, function(elm, callback) {
	console.log('processing element: ' + elm);
	if (elm % 2 === 0) {
		callback();
	}
	if (elm % 2 !== 0) {
		callback("odd number encountered");
	}
}, 
function(err) {
	if (err) {
		console.log(err);
	}
	else {
		console.log("nothing to report");
	}
});
```

From my understanding, async.each operates on all elements in parallel and therefore each odd element encountered should fire a callback with an error, instead the output I get the output below. Is this expected behavior?

```
processing element: 1
odd number encountered
processing element: 2
processing element: 3
processing element: 4
processing element: 5
processing element: 6
processing element: 7
processing element: 8
```

**Comment by bao987654321** [comment]
This is the expected behavior. The final callback is only called once, either on the first error or when all the iterator functions finish.

**Comment by AliUz** [comment]
So, in this case, if I want processing to stop after I encounter an error, I guess I should use eachSeries instead?

**Comment by aearly** [comment]
Yes, `eachSeries` will prevent further execution.

One thing to note isthat `each` doesn't execute any JS code in parallel, it just kicks off a bunch of I/O tasks in parallel.  Since your functions here are actually synchronous (call theif callbacks on the same tick) and don't do any I/O they actually are executed in a similar manner to `[].forEach`.
