### ISSUE TITLE
eachSeries - next (callback) function doesn't work sometimes

### ISSUE THREAD

**Issue by decoursin** [caolan/async#820]
````
		loggedInPromise.then(function (_) {
			return async.eachSeries(config.Ids, function (bookId, next) {
				var book = {};
				book.Id = bookId;
				book.index = index;

				share.goToBookPage(book).
					then(rentBook).
					thenCatch(catchException).
					then(next);  // fails
//					then(function () {
//						next(); // works here
//					});
			}, function (err) {
				console.log("seems like an error", err);
			});
````
In this code, if I do then(next), it fails to work properly. The result is that none of the succeeding array members are iterated over; instead, it goes straight to function (err) {...}. However, if I wrap the next in a function body as commented out above, it works as expected.

I should be able to say then(next), right? I have this expectation because other async libraries can do things like: then(done).

Thank you.

**Comment by aearly** [comment]
For most Promise implementations, `then`  has a signture of `function then(onResolved, onRejected) {}`, where `onResolved` is of the form `onResolved(value)`.  In `eachSeries` and other node callbacks, the callback is of the form `done(err, values...)`, which will cause the series to abort if that first `err` value is truthy.

Just make sure you pass no args to `done()` or `done(null, value)` and you should be okay.

At a higher level,  you might be better off using `Promise.all(config.Ids.map(createYourPromiseHere)`  rather than trying to shoehorn in `async.eachSeries` -- Promises and async don't entirely play nicely together, as you see here.

**Comment by decoursin** [comment]
Although maybe there exists a better alternative (for me here) than `async.eachSeries`, your suggestion isn't it. Not shown here but I'm using selenium webdriver, and I must iterate over each id item strictly in sequence not in parallel - the second one must come after the first one finishes asynchronously. To me, it seems that eachSeries is exactly what I need.

Can you please look at my updated code below? I just want to make sure we're on the same page because it doesn't quite feel like it.

There was a slight error in my original code (because I removed the outer context and cut some things out for this example), so I'm pasting in a corrected form below. Sorry about this.

````
		loggedInPromise.then(function (done) {
			async.eachSeries(config.Ids, function (bookId, next) {
				var book = {};
				book.Id = bookId;
				book.index = index;

				share.goToBookPage(book).
					then(rentBook).
					thenCatch(catchException).
					then(next);  // fails, jumps to function (err) {...} without going to the next id.
//					then(function () {
//						next(); // works here, but then(next) should work.
//					});
			}, function (err) {
				console.log("seems like an error", err);
                                done();
			});
              });
````

**Comment by aearly** [comment]
`then(next)`  won't work.  Do what you've commented out.

**Comment by decoursin** [comment]
Alright

**Comment by aearly** [comment]
We're not going to do that -- the `onResolved` callback for a Promise isn't a node-style callback (`function(value) {}` rather than `function (err, value) {}`).

Also, depending on your promise implementation, you might have [`Promise.reduce`](https://github.com/petkaantonov/bluebird/blob/master/API.md#reducefunction-reducer--dynamic-initialvalue---promise), which would iterate over a list of items in sequence:

```js
Promise.reduce(config.Ids, function(results, id) {
  var book = {};
  book.Id = id;
  book.index = index;

  return share.goToBookPage(book).
      then(rentBook).
      thenCatch(catchException);

}, []).then(function () {
  // done iterating
});
```

**Comment by decoursin** [comment]
Thank you and for the suggestion.

**Comment by decoursin** [comment]
With generators:

````
		for (var id of config.Ids) {
			var book = {};
			book.Id = asin;
			try {
				yield client.
						goToBookPage(book).
						rentBook(book);
			} catch (e) {
				logger.info(e);
				assert.fail(null,null,e.message);
			}
		}
````
