### ISSUE TITLE
I guess I found one bug in async.whilst

### ISSUE THREAD

**Issue by bittecnologia** [caolan/async#860]
Folks, when I used the async.whilst the function where I inserted the code restarted wihout reason when I used a "loop" so long, example

       this.myfunction= function (number, callback) {
            var count=0; 
            async.whilst (
            function () {             
                return count< 5000;
            },
            function (asyncCallback) {              
                    count++;
                    asyncCallback();
                });

            },
            function (err) {
                callback('something');
            }
          );
        };

When I changed to async.until it worked!

**Comment by charlierudolph** [comment]
The javascript you provided isn't valid. It also doesn't use its first parameter number.

Making some assumptions, running myfunction does error with `RangeError: Maximum call stack size exceeded`. However is you make the async function actually asynchronous with
```js
function (asyncCallback) {              
  count++;
  process.nextTick(asyncCallback);
});
```
then it works just fine.

`async.until` works because the first test fails and thus it never has a chance to exceed the callstack.

This is related to #696. But it is also documented on the [README](https://github.com/caolan/async#common-pitfalls-stackoverflow)

Please expand if you were running into a different problem
